print("Welcome to the WolfOS installer!")
os.sleep(0.1)
print("Installing...")
os.sleep(1)

if fs.exists("/WolfOS") then
  printError("WolfOS is already installed.")
  printError("Reinstalling...")
  fs.delete("/WolfOS/Menu.lua")
  fs.delete("/WolfOS/BootMenu.lua")
  fs.delete("/WolfOS/Mainmenu.lua")
  fs.delete("/WolfOS/Dprogs.lua")
  fs.delete("/WolfOS/Rprogs.lua")
  fs.delete("/WolfOS/Exit.lua")
  fs.delete("/WolfOS/ver.txt")
  fs.delete("/WolfOS/Update.lua")
  fs.delete("/WolfOS/Reinstaller")
  shell.run("cd /WolfOS")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Menu.lua Menu.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/BootMenu.lua BootMenu.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Mainmenu.lua Mainmenu.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Dprogs.lua Dprogs.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Rprogs.lua Rprogs.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Exit.lua Exit.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/ver.txt ver.txt")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Update.lua Update.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Reinstaller.lua Reinstaller.lua")
else
  fs.makeDir("/WolfOS")
  shell.run("cd /WolfOS")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Menu.lua Menu.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/BootMenu.lua BootMenu.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Mainmenu.lua Mainmenu.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Dprogs.lua Dprogs.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Rprogs.lua Rprogs.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Exit.lua Exit.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/ver.txt ver.txt")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Update.lua Update.lua")
  shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Reinstaller.lua Reinstaller.lua")
end
