fs.delete("/WolfOS/Menu.lua")
fs.delete("/WolfOS/BootMenu.lua")
fs.delete("/WolfOS/Mainmenu.lua")
fs.delete("/WolfOS/Dprogs.lua")
fs.delete("/WolfOS/Rprogs.lua")
fs.delete("/WolfOS/Exit.lua")
fs.delete("/WolfOS/ver.txt")
shell.run("cd /WolfOS")
shell.run("cd /WolfOS")
shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Menu.lua Menu.lua")
shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/BootMenu.lua BootMenu.lua")
shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Mainmenu.lua Mainmenu.lua")
shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Dprogs.lua Dprogs.lua")
shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Rprogs.lua Rprogs.lua")
shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/Exit.lua Exit.lua")
shell.run("wget https://raw.githubusercontent.com/LeWolfYT/CC-Tweaked-WolfOS/main/WolfOS/ver.txt ver.txt")
shell.run("/WolfOS/Menu.lua")
